version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taskmanager_app
    restart: always
    command: npm run start
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - rabbitmq
    environment:
      DATABASE_URL: ${DATABASE_URL}
      RABBITMQ_URL: ${RABBITMQ_URL}
      JWT_SECRET: ${JWT_SECRET}
      NODE_ENV: ${NODE_ENV}